import { writeFileSync, mkdirSync } from 'node:fs';
import { resolve } from 'node:path';
import {
  fetchIntermediateRepresentation,
  IR_URL,
  outDir,
  propKey,
} from './shared.js';
import { WebScrapingApiIR } from './types';

export const getParametersFile = (api: WebScrapingApiIR): string => {
  const lines: string[] = [];

  lines.push(
    '// Auto-generated by codegen/web-scraping-api/generate-parameters.ts — do not edit',
  );
  lines.push('');

  lines.push('export type ParameterMeta = {');
  lines.push('  type: string;');
  lines.push('  maxLength?: number;');
  lines.push('  min?: number;');
  lines.push('  max?: number;');
  lines.push('  enum?: (string | number)[];');
  lines.push('  items?: { type: string };');
  lines.push('};');
  lines.push('');

  lines.push('export const parameterMeta: Record<string, ParameterMeta> = {');
  for (const [key, param] of Object.entries(api.parameters)) {
    const parts: string[] = [];
    parts.push(`type: ${JSON.stringify(param.type)}`);
    if (param.maxLength !== undefined) {
      parts.push(`maxLength: ${param.maxLength}`);
    }
    if (param.min !== undefined) {
      parts.push(`min: ${param.min}`);
    }
    if (param.max !== undefined) {
      parts.push(`max: ${param.max}`);
    }
    if (param.enum) {
      parts.push(
        `enum: [${param.enum.map((v) => JSON.stringify(v)).join(', ')}]`,
      );
    }
    if (param.items) {
      parts.push(`items: { type: ${JSON.stringify(param.items.type)} }`);
    }
    lines.push(`  ${propKey(key)}: { ${parts.join(', ')} },`);
  }
  lines.push('};');
  lines.push('');

  return lines.join('\n');
};

export const generateParametersFile = async () => {
  const ir = await fetchIntermediateRepresentation();
  const fileContents = getParametersFile(ir.apis.webScrapingApi);

  mkdirSync(outDir, { recursive: true });

  writeFileSync(resolve(outDir, 'parameters.ts'), fileContents);

  console.log(`Generated parameters from ${IR_URL}:`);

  console.log(
    `  ${resolve(outDir, 'parameters.ts')} (${
      Object.keys(ir.apis.webScrapingApi.parameters).length
    } parameters)`,
  );
};
