import { mkdirSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import * as z from 'zod';
import {
  fetchIntermediateRepresentation,
  localIrPath,
  outDir,
  toEnumMemberName,
} from './shared.js';
import type { WebScrapingApiIR } from './types.js';

const renderGeneratedModule = (api: WebScrapingApiIR): string => {
  const entries = Object.entries(api.targets);
  const lines: string[] = [];

  lines.push(
    '// Auto-generated by codegen/web-scraping-api/generate-parameter-schemas.ts — do not edit',
  );
  lines.push('');
  lines.push("import * as z from 'zod';");
  lines.push("import { Target } from './targets.js';");
  lines.push('');
  lines.push('export const requestJsonSchemas = {');
  for (const [targetKey, target] of entries) {
    const schemaLiteral = JSON.stringify(target.parameter_schema, null, 2)
      .split('\n')
      .map((line, idx) => (idx === 0 ? line : `  ${line}`))
      .join('\n');
    lines.push(`  [Target.${toEnumMemberName(targetKey)}]: ${schemaLiteral},`);
  }
  lines.push('} as const;');
  lines.push('');
  lines.push('export const requestSchemas: Record<Target, z.ZodType> = {');
  for (const [targetKey] of entries) {
    const member = toEnumMemberName(targetKey);
    lines.push(
      `  [Target.${member}]: z.fromJSONSchema(requestJsonSchemas[Target.${member}] as unknown as z.core.JSONSchema.JSONSchema),`,
    );
  }
  lines.push('};');
  lines.push('');
  return lines.join('\n');
};

export const generateParameterSchemasFile = async (): Promise<void> => {
  const ir = await fetchIntermediateRepresentation();
  const api = ir.apis.webScrapingApi;

  for (const [targetKey, target] of Object.entries(api.targets)) {
    try {
      z.fromJSONSchema(
        target.parameter_schema as unknown as z.core.JSONSchema.JSONSchema,
      );
    } catch (err) {
      throw new Error(
        `Invalid parameter_schema for target "${targetKey}": ${(err as Error).message}`,
      );
    }
  }

  mkdirSync(outDir, { recursive: true });
  const outPath = resolve(outDir, 'request-schemas.ts');
  writeFileSync(outPath, renderGeneratedModule(api));

  console.log(`Generated request schemas from ${localIrPath}:`);
  console.log(`  ${outPath} (${Object.keys(api.targets).length} targets)`);
};
