import { writeFileSync, mkdirSync } from 'node:fs';
import { resolve } from 'node:path';
import { compile } from 'json-schema-to-typescript';
import {
  getTargetEnumSchema,
  getTargetParamsSchema,
  compileOpts,
  fetchIntermediateRepresentation,
  IR_URL,
  outDir,
  toEnumMemberName,
  toPascalCase,
} from './shared.js';
import { WebScrapingApiIR } from './types';

const getTargetsFileContents = async (
  api: WebScrapingApiIR,
): Promise<string> => {
  const lines: string[] = [];

  lines.push(
    '// Auto-generated by codegen/web-scraping-api/generate-targets.ts — do not edit',
  );
  lines.push('');

  const targetKeys = Object.keys(api.targets);
  const targetEnumBlock = await compile(
    getTargetEnumSchema(targetKeys),
    'Target',
    compileOpts,
  );
  lines.push(targetEnumBlock.trimEnd());
  lines.push('');
  lines.push(
    '/** API discriminator string literals (same values as {@link Target}). */',
  );
  lines.push(
    'export type TargetString = (typeof Target)[keyof typeof Target];',
  );
  lines.push('');

  lines.push(
    `export const targets = [${targetKeys
      .map((k) => `Target.${toEnumMemberName(k)}`)
      .join(', ')}] as const;`,
  );
  lines.push('');

  for (const [targetKey, target] of Object.entries(api.targets)) {
    const typeName = `${toPascalCase(targetKey)}Params`;
    const schema = getTargetParamsSchema(api, target);
    const block = await compile(schema, typeName, compileOpts);
    lines.push(block.trimEnd());
    lines.push('');
  }

  lines.push('export type TargetParamsMap = {');
  for (const targetKey of targetKeys) {
    const typeName = `${toPascalCase(targetKey)}Params`;
    lines.push(`  [Target.${toEnumMemberName(targetKey)}]: ${typeName};`);
  }
  lines.push('};');
  lines.push('');

  lines.push('export type ScrapeRequest = {');
  lines.push('  [T in TargetString]: { target: T } & TargetParamsMap[T];');
  lines.push('}[TargetString];');
  lines.push('');

  lines.push('export type BatchRequest = {');
  lines.push(
    '  [T in TargetString]: { target: T; url?: string[]; query?: string[] } & Omit<TargetParamsMap[T], "url" | "query">;',
  );
  lines.push('}[TargetString];');
  lines.push('');

  lines.push('export type TargetMeta = {');
  lines.push('  group: string;');
  lines.push('  responseFormat: string;');
  lines.push('  parameters: string[];');
  lines.push('};');
  lines.push('');
  lines.push('export const targetMeta: Record<Target, TargetMeta> = {');
  for (const [targetKey, target] of Object.entries(api.targets)) {
    lines.push(`  [Target.${toEnumMemberName(targetKey)}]: {`);
    lines.push(`    group: ${JSON.stringify(target.group)},`);
    lines.push(`    responseFormat: ${JSON.stringify(target.responseFormat)},`);
    lines.push(
      `    parameters: [${target.parameters
        .map((p) => JSON.stringify(p))
        .join(', ')}],`,
    );
    lines.push('  },');
  }
  lines.push('};');
  lines.push('');

  return lines.join('\n');
};

export const generateTargetsFile = async () => {
  const ir = await fetchIntermediateRepresentation();
  const fileContents = await getTargetsFileContents(ir.apis.webScrapingApi);

  mkdirSync(outDir, { recursive: true });

  writeFileSync(resolve(outDir, 'targets.ts'), fileContents);

  console.log(`Generated targets from ${IR_URL}:`);

  console.log(
    `  ${resolve(outDir, 'targets.ts')} (${Object.keys(ir.apis.webScrapingApi.targets).length} targets)`,
  );
};
