import { writeFileSync, mkdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { compile } from 'json-schema-to-typescript';
import type { JSONSchema4 } from 'json-schema';

const __dirname = dirname(fileURLToPath(import.meta.url));

// todo: update to permanent IR location
const IR_URL =
  'https://gist.githubusercontent.com/domantas-jurkus-dcd/43c47a102bcdf97842814d635ba47f05/raw/3b9e4a35f05ada3f8ed4410376f59ad89b4e6535/config.json';
const outDir = resolve(__dirname, '../src/generated');

const compileOpts = {
  bannerComment: '',
  format: true,
  style: {
    singleQuote: true,
    semi: true,
    trailingComma: 'none' as const,
    tabWidth: 2,
  },
};

type IRParameter = {
  type: string;
  maxLength?: number;
  min?: number;
  max?: number;
  enum?: (string | number)[];
  items?: { type: string };
};

type IRTarget = {
  group: string;
  responseFormat: string;
  parameters: string[];
};

type IRApi = {
  label: string;
  baseUrl: string;
  auth: { type: string; [key: string]: unknown };
  endpoints: Record<
    string,
    { method: string; path: string; description: string }
  >;
  parameters: Record<string, IRParameter>;
  targets: Record<string, IRTarget>;
};

type IR = {
  version: string;
  apis: Record<string, IRApi>;
};

const toPascalCase = (s: string): string =>
  s
    .replace(/([a-z])([A-Z])/g, '$1_$2')
    .split(/[_\s-]+/)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
    .join('');

/** PascalCase identifier safe for `enum Target { … }` members (e.g. keys starting with digits). */
const toEnumMemberName = (targetKey: string): string => {
  const pascal = toPascalCase(targetKey);
  if (/^[0-9]/.test(pascal) || !/^[A-Za-z_$]/.test(pascal)) {
    return `_${pascal}`;
  }
  return pascal;
};

const isValidIdentifier = (key: string): boolean =>
  /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(key);

const propKey = (key: string): string =>
  isValidIdentifier(key) ? key : JSON.stringify(key);

const parameterToJsonSchema = (param: IRParameter): JSONSchema4 => {
  const type = param.type as JSONSchema4['type'];
  const schema: JSONSchema4 = { type };

  if (param.maxLength !== undefined) {
    schema.maxLength = param.maxLength;
  }
  if (param.min !== undefined) {
    schema.minimum = param.min;
  }
  if (param.max !== undefined) {
    schema.maximum = param.max;
  }
  if (param.enum) {
    schema.enum = param.enum;
  }
  if (param.type === 'array' && param.items) {
    schema.items = parameterToJsonSchema(param.items as IRParameter);
  }
  if (param.type === 'object') {
    schema.additionalProperties = { type: 'string' };
  }

  return schema;
};

const buildTargetParamsSchema = (api: IRApi, target: IRTarget): JSONSchema4 => {
  const properties: Record<string, JSONSchema4> = {};
  for (const paramKey of target.parameters) {
    const param = api.parameters[paramKey];
    if (!param) {
      continue;
    }
    properties[paramKey] = parameterToJsonSchema(param);
  }
  return {
    type: 'object',
    properties,
    additionalProperties: false,
  };
};

const generateTargetsFile = async (api: IRApi): Promise<string> => {
  const lines: string[] = [];

  lines.push('// Auto-generated by codegen/generate-from-ir.ts — do not edit');
  lines.push('');

  const targetKeys = Object.keys(api.targets);
  lines.push('export enum Target {');
  for (const targetKey of targetKeys) {
    lines.push(
      `  ${toEnumMemberName(targetKey)} = ${JSON.stringify(targetKey)},`,
    );
  }
  lines.push('}');
  lines.push('');
  lines.push(
    '/** API discriminator string literals (same values as {@link Target}). */',
  );
  lines.push(
    'export type TargetString = (typeof Target)[keyof typeof Target];',
  );
  lines.push('');

  lines.push(
    `export const targets = [${targetKeys
      .map((k) => `Target.${toEnumMemberName(k)}`)
      .join(', ')}] as const;`,
  );
  lines.push('');

  for (const [targetKey, target] of Object.entries(api.targets)) {
    const typeName = `${toPascalCase(targetKey)}Params`;
    const schema = buildTargetParamsSchema(api, target);
    const block = await compile(schema, typeName, compileOpts);
    lines.push(block.trimEnd());
    lines.push('');
  }

  lines.push('export type TargetParamsMap = {');
  for (const targetKey of targetKeys) {
    const typeName = `${toPascalCase(targetKey)}Params`;
    lines.push(`  [Target.${toEnumMemberName(targetKey)}]: ${typeName};`);
  }
  lines.push('};');
  lines.push('');

  lines.push('export type ScrapeRequest = {');
  lines.push(
    '  [T in TargetString]: { target: T } & TargetParamsMap[T];',
  );
  lines.push('}[TargetString];');
  lines.push('');

  lines.push('export type BatchRequest = {');
  lines.push(
    '  [T in TargetString]: { target: T; url?: string[]; query?: string[] } & Omit<TargetParamsMap[T], "url" | "query">;',
  );
  lines.push('}[TargetString];');
  lines.push('');

  lines.push('export type TargetMeta = {');
  lines.push('  group: string;');
  lines.push('  responseFormat: string;');
  lines.push('  parameters: string[];');
  lines.push('};');
  lines.push('');
  lines.push('export const targetMeta: Record<Target, TargetMeta> = {');
  for (const [targetKey, target] of Object.entries(api.targets)) {
    lines.push(`  [Target.${toEnumMemberName(targetKey)}]: {`);
    lines.push(`    group: ${JSON.stringify(target.group)},`);
    lines.push(`    responseFormat: ${JSON.stringify(target.responseFormat)},`);
    lines.push(
      `    parameters: [${target.parameters
        .map((p) => JSON.stringify(p))
        .join(', ')}],`,
    );
    lines.push('  },');
  }
  lines.push('};');
  lines.push('');

  return lines.join('\n');
};

const generateParametersFile = (api: IRApi): string => {
  const lines: string[] = [];

  lines.push('// Auto-generated by codegen/generate-from-ir.ts — do not edit');
  lines.push('');

  lines.push('export type ParameterMeta = {');
  lines.push('  type: string;');
  lines.push('  maxLength?: number;');
  lines.push('  min?: number;');
  lines.push('  max?: number;');
  lines.push('  enum?: (string | number)[];');
  lines.push('  items?: { type: string };');
  lines.push('};');
  lines.push('');

  lines.push('export const parameterMeta: Record<string, ParameterMeta> = {');
  for (const [key, param] of Object.entries(api.parameters)) {
    const parts: string[] = [];
    parts.push(`type: ${JSON.stringify(param.type)}`);
    if (param.maxLength !== undefined) {
      parts.push(`maxLength: ${param.maxLength}`);
    }
    if (param.min !== undefined) {
      parts.push(`min: ${param.min}`);
    }
    if (param.max !== undefined) {
      parts.push(`max: ${param.max}`);
    }
    if (param.enum) {
      parts.push(
        `enum: [${param.enum.map((v) => JSON.stringify(v)).join(', ')}]`,
      );
    }
    if (param.items) {
      parts.push(`items: { type: ${JSON.stringify(param.items.type)} }`);
    }
    lines.push(`  ${propKey(key)}: { ${parts.join(', ')} },`);
  }
  lines.push('};');
  lines.push('');

  return lines.join('\n');
};

// ---- main ----

const fetchIr = async (): Promise<IR> => {
  const res = await fetch(IR_URL);
  if (!res.ok) {
    throw new Error(
      `Failed to fetch IR: ${res.status} ${res.statusText} (${IR_URL})`,
    );
  }
  return res.json() as Promise<IR>;
};

const ir = await fetchIr();
const webScrapingApi = ir.apis.webScrapingApi;
if (!webScrapingApi) {
  throw new Error(
    `IR must define apis.webScrapingApi (found: ${Object.keys(ir.apis).join(', ')})`,
  );
}

mkdirSync(outDir, { recursive: true });
writeFileSync(
  resolve(outDir, 'targets.ts'),
  await generateTargetsFile(webScrapingApi),
);
writeFileSync(
  resolve(outDir, 'parameters.ts'),
  generateParametersFile(webScrapingApi),
);

console.log(`Generated from ${IR_URL}:`);
console.log(
  `  ${outDir}/targets.ts (${Object.keys(webScrapingApi.targets).length} targets)`,
);
console.log(
  `  ${outDir}/parameters.ts (${
    Object.keys(webScrapingApi.parameters).length
  } parameters)`,
);
